# Generated by Django 4.0.3 on 2022-04-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0004_task_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='posted_by',
        ),
        migrations.AddField(
            model_name='task',
            name='added_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
