# Generated by Django 4.0.3 on 2022-04-06 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0008_task_prio'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='proceed_till',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='task',
            name='prio',
            field=models.CharField(choices=[('low', 'low'), ('regular', 'regular'), ('high', 'high')], default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in pipeline', 'in pipeline'), ('done', 'done')], default='in pipeline', max_length=20),
        ),
    ]
