# Generated by Django 4.0.3 on 2022-04-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0009_task_proceed_till_alter_task_prio_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='main_project',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
