# Generated by Django 4.0.3 on 2022-04-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0002_rename_descirption_task_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in pipeline', 'work in progress'), ('done', 'task completed')], default='in pipeline', max_length=20),
        ),
    ]
